config/routes.rb
Rails.application.routes.draw do
  root to: 'schedules#index'
  get '/schedules/new', to: "schedules#new"
  post '/schedules', to: "schedules#create"
  get '/schedules/:id', to: "schedules#show"
  get '/schedules/:id/edit', to: "schedules#edit"
  patch '/schedules/:id', to: "schedules#update"
  delete '/schedules/:id', to: 'schedules#destroy'
  devise_for :users, controllers: {
      sessions:      'users/sessions',
      passwords:     'users/passwords',
      registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user

  validates :pickup_date, presence: true
  validates :delivery_date, presence: true
  validates :cy, presence: true
  validates :warehouse, presence: true
  validates :bill_number, presence: true
  validates :container, presence: true
  validates :size, presence: true
  validates :container_type, presence: true
  validates :transporter, presence: true
  validates :customer, presence: true
  validates :reference_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :schedules, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[edit update destroy]

  def index
    @schedules = Schedule.includes(:user).order(:pickup_date)
  end

  def new
    @schedule = Schedule.new
  end

  def create
    schedule = current_user.schedules.create(schedule_params)
    redirect_to root_path
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule.update!(schedule_params)
    redirect_to root_path
  end

  def destroy
    @schedule.destroy!
    redirect_to root_path
  end

  private
  def schedule_params
    params.require(:schedule).permit(:pickup_date, :delivery_date, :allowed_time, :cy, :warehouse, :bill_number, :container, :size, :axis, :transporter, :division, :customer, :reference_number, :trade_type, :container_type, :customer_reference)
  end

  def set_schedule
    @schedule = current_user.schedules.find_by(id: params[:id])
    redirect_to root_path, alert: "権限がありません！" if @schedule.nil?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar fixed-bottom bg-primary text-light d-flex justify-content-center">
  <p>&copy; copyrights Kenichi Shimada</p>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-bav fixed-top bg-danger text-light">  
  <div>
    <span class="badge badge-danger border">Dr.M</span>
  </div>
  <div class="text-left">
    <h3>Drayage Manager</h3>
  </div>
  <div>
    <% if user_signed_in? %>
      <%# ログイン時 %>
      <%= link_to "TOP", root_path, class:"text-light" %>
      <%= link_to "投稿画面へ", schedules_new_path, class:"text-light" %>
      <%= link_to "アカウント編集", edit_user_registration_path, class:"text-light" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class:"text-light" %>
      <%= "【ログイン名】#{current_user.username}" %>
    <% else %>
      <%# 非ログイン時 %>
      <%= link_to "新規登録", new_user_registration_path, class:"text-light" %>
      <%= link_to "ログイン", new_user_session_path, class:"text-light" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrayageManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container text-center">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/schedules/create.html.erb
<h1>登録完了！</h1>
<%= link_to '一覧へ戻る', root_path %>

app/views/schedules/destroy.html.erb
<h1>削除完了！</h1>
<%= link_to '一覧へ戻る', root_path %>

app/views/schedules/edit.html.erb
<h1>スケジュール変更・編集</h1>
<%= form_with model: @schedule, url: "/schedules/#{@schedule.id}", method: :patch, local: true do |f| %>
  <table class="table table-dark">
    <tr>
      <th><%= f.label :pickup_date, "搬出日*" %></th>
      <td><%= f.text_field :pickup_date %></td>
      <th><%= f.label :delivery_date, "納品日*" %></th>
      <td><%= f.text_field :delivery_date %></td>
      <th><%= f.label :allowed_time, "納品時間" %></th>
      <td><%= f.text_field :allowed_time %></td>
    </tr>
    <tr>
      <th><%= f.label :cy, "CY*" %></th>
      <td><%= f.text_field :cy %></td>
      <th><%= f.label :warehouse, "倉庫名*" %></th>
      <td><%= f.text_field :warehouse %></td>
    </tr>
    <tr>
      <th><%= f.label :bill_number, "B/L NO.*" %></th>
      <td><%= f.text_field :bill_number %></td>
      <th><%= f.label :container, "VAN NO.*" %></th>
      <td><%= f.text_field :container %></td>
    </tr>
    <tr>
      <th><%= f.label :size, "サイズ*" %></th>
      <td><%= f.select :size, [["20", "20"], ["40", "40"]], include_blank: "選択してください" %></td>
      <th><%= f.label :axis, "軸数*" %></th>
      <td><%= f.select :axis, [["2軸", "2軸"], ["3軸", "3軸"]], include_blank: "選択してください" %></td>
      <th><%= f.label :container_type, "タイプ*" %></th>
      <td><%= f.select :container_type, [["DRY", "DRY"], ["REEFER", "REEFER"],["OPEN TOP", "OPEN TOP"],["FLAT RACK", "FLAT RACK"],["TANK", "TANK"]], include_blank: "選択してください" %></td>
      </tr>
      <tr>
      <th><%= f.label :transporter, "運送会社" %></th>
      <td><%= f.text_field :transporter %></td>
      <th><%= f.label :trade_type, "輸出入" %></th>
      <td><%= f.select :trade_type, [["輸出", "輸出"], ["輸入", "輸入"]], include_blank: "選択してください" %></td>
    </tr>
    <tr>
      <th><%= f.label :reference_number, "管理番号" %></th>
      <td><%= f.text_field :reference_number %></td>
      <th><%= f.label :division, "扱い部署名" %></th>
      <td><%= f.text_field :division %></td>
    </tr>
    <tr>
      <th><%= f.label :customer, "荷主名*" %></th>
      <td><%= f.text_field :customer %></td>
      <th><%= f.label :customer_reference, "荷主REF NO." %></th>
      <td><%= f.text_field :customer_reference %></td>
    </tr>
  </table>
  <p>* は必須入力！</p>
  <%= f.submit "更新" %>
<% end %>

app/views/schedules/index.html.erb
<% if user_signed_in? %>
  <h1>Container Schedule List</h1>
  <div class="card">
      <div class="card-body d-flex row">
        <div class="col-8">
          <div>
            <h3 class="card-title">Container NO.</h3>
          </div>
        </div>
        <div class="col">
          <h3>SIZE   TYPE </h3>
        </div>
      </div>
    </div>
  <% @schedules.each do |s| %>
    <div class="card">
      <div class="card-body d-flex row">
        <div class="col-8">
          <div>
            <h3 class="card-title"><%= s.container %></h3>
          </div>
          <div>
            <span><%= s.pickup_date %></span> PICK  
            <span><%= s.cy %></span> → 
            <span><%= s.warehouse %></span> 
            <%= s.transporter %>
          </div>
          <div>
            <span><%= s.reference_number %></span>
            <%= s.customer %>
            <span><%= s.customer_reference %></span>
          </div>
        </div>
        <div class="col">
          <h3><%= s.size %>F   <%= s.container_type %> </h3>
          <div class="d-flex justify-content-center">
            <%= link_to '詳細', "/schedules/#{s.id}", class:"btn btn-success" %>
            <%= link_to '編集', "/schedules/#{s.id}/edit", method: :get, class:"btn btn-success"  %>
            <%= link_to '削除', "/schedules/#{s.id}", method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/schedules/new.html.erb
<h1>スケジュール登録</h1>
<%= form_with model: @schedule, local: true do |f| %>
  <table class="table table-dark">
    <tr>
      <th><%= f.label :pickup_date, "搬出日*" %></th>
      <td><%= f.text_field :pickup_date %></td>
      <th><%= f.label :delivery_date, "納品日*" %></th>
      <td><%= f.text_field :delivery_date %></td>
      <th><%= f.label :allowed_time, "納品時間" %></th>
      <td><%= f.text_field :allowed_time %></td>
    </tr>
    <tr>
      <th><%= f.label :cy, "CY*" %></th>
      <td><%= f.text_field :cy %></td>
      <th><%= f.label :warehouse, "倉庫名*" %></th>
      <td><%= f.text_field :warehouse %></td>
    </tr>
    <tr>
      <th><%= f.label :bill_number, "B/L NO.*" %></th>
      <td><%= f.text_field :bill_number %></td>
      <th><%= f.label :container, "VAN NO.*" %></th>
      <td><%= f.text_field :container %></td>
    </tr>
    <tr>
      <th><%= f.label :size, "サイズ*" %></th>
      <td><%= f.select :size, [["20", "20"], ["40", "40"]], include_blank: "選択してください" %></td>
      <th><%= f.label :axis, "軸数*" %></th>
      <td><%= f.select :axis, [["2軸", "2軸"], ["3軸", "3軸"]], include_blank: "選択してください" %></td>
      <th><%= f.label :container_type, "タイプ*" %></th>
      <td><%= f.select :container_type, [["DRY", "DRY"], ["REEFER", "REEFER"],["OPEN TOP", "OPEN TOP"],["FLAT RACK", "FLAT RACK"],["TANK", "TANK"]], include_blank: "選択してください" %></td>
      </tr>
      <tr>
      <th><%= f.label :transporter, "運送会社*" %></th>
      <td><%= f.text_field :transporter %></td>
      <th><%= f.label :trade_type, "輸出入" %></th>
      <td><%= f.select :trade_type, [["輸出", "輸出"], ["輸入", "輸入"]], include_blank: "選択してください" %></td>
    </tr>
    <tr>
      <th><%= f.label :reference_number, "管理番号*" %></th>
      <td><%= f.text_field :reference_number %></td>
      <th><%= f.label :division, "扱い部署名" %></th>
      <td><%= f.text_field :division %></td>
    </tr>
    <tr>
      <th><%= f.label :customer, "荷主名*" %></th>
      <td><%= f.text_field :customer %></td>
      <th><%= f.label :customer_reference, "荷主REF NO." %></th>
      <td><%= f.text_field :customer_reference %></td>
    </tr>
  </table>
  <p>* は必須入力！</p>
  <%= f.submit "登録" %>
<% end %>

app/views/schedules/show.html.erb
<% if user_signed_in? %>
  <h1>スケジュール詳細</h1>
  <table class="table table-dark">
    <tr>
      <th>搬出日</th>
      <td><%= @schedule.pickup_date %></td>
      <th>CY</th>
      <td><%= @schedule.cy %></td>
    </tr>
    <tr>
      <th>納品日・時間</th>
      <td><%= @schedule.delivery_date %> <%= @schedule.allowed_time %></td>
      <th>倉庫名</th>
      <td><%= @schedule.warehouse %></td>
    </tr>
    <tr>
      <th>B/L NO.</th>
      <td><%= @schedule.bill_number %></td>
    </tr>
    <tr>
      <th>コンテナNO.</th>
      <td><%= @schedule.container %></td>
      <th>
        <p>サイズ</p>
        <p>軸数</p>
        <p>コンテナタイプ</p>
      </th>
      <td>
        <p><%= @schedule.size %></p>
        <p><%= @schedule.axis %></p>
        <p><%= @schedule.container_type %></p>
      </td>
    </tr>
    <tr>
      <th>運送会社</th>
      <td><%= @schedule.transporter %></td>
    </tr>
    <tr>
      <th>荷主</th>
      <td><%= @schedule.customer %></td>
    </tr>
    <tr>
      <th>管理番号</th>
      <td><%= @schedule.reference_number %></td>
    </tr>
  </table>
<% else %>
  <p>ログインしてください</p>
<% end %>

app/views/schedules/update.html.erb
<h1>更新完了！</h1>
<%= link_to '一覧へ戻る', root_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "アカウントをお持ちでない方はこちらへ", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れの方はこちらへ", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>